# Generated by Django 2.0.4 on 2018-11-12 18:53

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockee', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cn_number', models.IntegerField(default=0, null=True)),
                ('class_name', models.CharField(max_length=200)),
                ('instructor', models.CharField(default='', max_length=100)),
                ('semester', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=6)),
                ('year', models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2018)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(default='', max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('max_members', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1)])),
                ('gender_specific', models.CharField(choices=[('U', 'Undeclared'), ('M', 'Male'), ('F', 'Female'), ('N', 'Nonbinary')], max_length=15)),
                ('days_available', models.CharField(default='', max_length=255)),
                ('hours_available_start', models.TimeField(blank=True, default=datetime.time(0, 1), null=True)),
                ('hours_available_end', models.TimeField(blank=True, default=datetime.time(23, 59), null=True)),
                ('online_only', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studygroups.Course')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroupFilter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studygroups.Filter')),
                ('studygroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studygroups.StudyGroup')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studygroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studygroups.StudyGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('schedule_abbreviation', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='studygroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studygroups.StudyGroup'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studygroups.Subject'),
        ),
    ]
