# Generated by Django 2.0.4 on 2018-11-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0002_auto_20181114_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_available', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='days_available',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='days_available',
            field=models.ManyToManyField(to='studygroups.Days'),
        ),
    ]
