# Generated by Django 2.0.4 on 2018-11-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0004_auto_20181124_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semesterchoices',
            old_name='days',
            new_name='semester',
        ),
    ]
