# Generated by Django 2.0.4 on 2018-11-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0005_auto_20181124_1930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DayChoices',
            new_name='DayChoice',
        ),
        migrations.RenameModel(
            old_name='GenderChoices',
            new_name='GenderChoice',
        ),
        migrations.RenameModel(
            old_name='SemesterChoices',
            new_name='SemesterChoice',
        ),
    ]
