# Generated by Django 2.0.4 on 2018-11-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0006_auto_20181124_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daychoice',
            old_name='days',
            new_name='day',
        ),
    ]
