# Generated by Django 2.0.4 on 2018-11-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0007_auto_20181124_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroupfilter',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='studygroupfilter',
            name='studygroup',
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
        migrations.DeleteModel(
            name='StudyGroupFilter',
        ),
    ]
