# Generated by Django 2.0.4 on 2018-11-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0008_auto_20181124_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genderchoice',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
