# Generated by Django 2.0.4 on 2018-11-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0009_auto_20181124_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='genderchoice',
            name='abbrev',
            field=models.CharField(default='U', max_length=1),
            preserve_default=False,
        ),
    ]
