# Generated by Django 2.0.4 on 2018-10-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181028_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('U', 'Undeclared'), ('M', 'Male'), ('F', 'Female'), ('N', 'Nonbinary')], max_length=1, null=True),
        ),
    ]
