# Generated by Django 2.0.4 on 2018-10-28 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('classSubject', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('college', models.CharField(default='humboldt.edu', max_length=200)),
                ('gender', models.CharField(max_length=1)),
                ('password', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('verificationCode', models.CharField(max_length=200)),
                ('verificationDate', models.DateTimeField(verbose_name='date verified')),
                ('acceptedTOS', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(verbose_name='date created')),
                ('adminUser', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='studygroup',
            name='creatorUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='studyGroupId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.StudyGroup'),
        ),
        migrations.AddField(
            model_name='message',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.User'),
        ),
    ]
