# Generated by Django 2.0.4 on 2018-10-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_auto_20181028_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='date',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
