# Generated by Django 2.0.4 on 2018-10-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20181028_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=6),
        ),
    ]
