# Generated by Django 2.0.4 on 2018-10-28 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_auto_20181028_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='classSubject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Subject'),
        ),
    ]
