# Generated by Django 2.0.4 on 2018-10-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_auto_20181028_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='year',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020)], default=2018),
        ),
    ]
