# Generated by Django 2.0.4 on 2018-10-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0011_auto_20181028_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studygroup',
            old_name='description',
            new_name='className',
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='year',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2018),
        ),
    ]
