# Generated by Django 2.0.4 on 2018-10-28 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0012_auto_20181028_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cNNumber', models.IntegerField(default=0)),
                ('className', models.CharField(max_length=200)),
                ('instructor', models.CharField(default='', max_length=100)),
                ('semester', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=6)),
                ('year', models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2018)),
                ('isActive', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Subject')),
            ],
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='cNNumber',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='className',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='classSubject',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='year',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Course'),
        ),
    ]
