# Generated by Django 2.0.4 on 2018-10-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0015_subject_scheduleabbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='scheduleAbbreviation',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
