# Generated by Django 2.0.4 on 2018-10-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0016_auto_20181028_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cNNumber',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
