# Generated by Django 2.0.4 on 2018-11-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0019_auto_20181105_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='postTitle',
            field=models.CharField(default='', max_length=250),
        ),
    ]
