# Generated by Django 2.0.4 on 2018-11-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0021_auto_20181107_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='wednesday',
        ),
    ]
