"""
Django settings for StudyPartnerFinder project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from django.conf.global_settings import EMAIL_BACKEND

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'abu8nj9#!p^%1^xr)65k9cp5o7qf_i=p_21r@@u=ns+fvnt781'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['no2.pythonanywhere.com', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'courses.apps.CoursesConfig',
    'studygroups.apps.StudygroupsConfig',
    'users.apps.UsersConfig',  # new
    'django_static_jquery',
    'accounts.apps.AccountsConfig',
    #'channels',
    #'chat',
    #'django_bootstrap_breadcrumbs'
]

# Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Host for sending e-mail.
EMAIL_HOST = 'smtp.mailtrap.io'

# Port for sending e-mail.
EMAIL_PORT = 465

# Optional SMTP authentication information for EMAIL_HOST.
EMAIL_HOST_USER = '2d2166773bc5ab'
EMAIL_HOST_PASSWORD = 'e1e694ae560b31'
EMAIL_USE_TLS = False

# We have custom user details, so point to our version of the User here.
AUTH_USER_MODEL = 'users.CustomUser'  # new

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'StudyPartnerFinder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'StudyPartnerFinder.wsgi.application'

# We only need ASGI if we enable chat.  
#ASGI_APPLICATION = 'StudyPartnerFinder.routing.application'
#CHANNEL_LAYERS = {
#    'default': {
#        'BACKEND': 'channels_redis.core.RedisChannelLayer',
#        'CONFIG': {
            #"hosts": [('127.0.0.1', 6379)],
            #"hosts": [('redis-11329.c60.us-west-1-2.ec2.cloud.redislabs.com', 11329)],
#            "hosts": ["redis://:qZOkKZ0GqiKAeqehJFsSzkoccX3WWO3G@redis-11329.c60.us-west-1-2.ec2.cloud.redislabs.com:11329/0"],
#            "symmetric_encryption_keys": [SECRET_KEY],
#        },
#    },
#}
#CACHES = {
#    'default': {
#                'BACKEND': 'redis_cache.RedisCache',
#                'LOCATION': 'redis-11329.c60.us-west-1-2.ec2.cloud.redislabs.com:11329',
#    'OPTIONS': {
#                'DB': 'StudyBuddy',
#                'PASSWORD': 'qZOkKZ0GqiKAeqehJFsSzkoccX3WWO3G'
#                }
#    }
#}

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'TEST': {
            'NAME': os.path.join(BASE_DIR, 'db_test.sqlite3')
            }
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
# STATIC_ROOT = '/home/no2/StudyPartnerFinder/StudyPartnerFinder/static/'
SITE_ROOT = os.path.dirname(os.path.realpath(__file__))
STATIC_ROOT = os.path.join( os.path.dirname ( __file__), os.path.pardir, 'static/')
STATIC_URL = '/static/'
STATICFILES_DIRS = (
  os.path.join(SITE_ROOT, 'static/'),
)

# LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/courses/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
