INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('American Indian Education', 'AIE');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Anthropology', 'ANTH');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Art', 'ART');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Arts, Humanities & Social Science', 'AHSS');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Biology', 'BIOL');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Botany', 'BOT');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Business Administration', 'BA');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Chemistry', 'CHEM');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Child Development', 'CD');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Chinese Studies', 'CHIN');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Communication', 'COMM');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Computer Science', 'CS');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Criminology & Justice Studies', 'CRIM');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Crit Race, Gender & Sexual Studies', 'CRGS');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Dance', 'DANC');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Economics', 'ECON');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Education', 'EDUC');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Educational Leadership', 'EDL');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Elementary Education', 'EED');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Engineering', 'ENGR');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('English', 'ENGL');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Environment and Community', 'EC');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Environmental Science Mgmt', 'ESM');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Environmental Studies', 'ENST');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Ethnic Studies', 'ES');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Film', 'FILM');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Fisheries', 'FISH');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Forest, Watershed & Wildlnd Science', 'FWWS');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Forestry', 'FOR');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('French', 'FREN');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Geography', 'GEOG');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Geology', 'GEOL');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Geospatial Analysis', 'GSP');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('German', 'GERM');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Health Education', 'HED');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('History', 'HIST');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('International Studies', 'INTL');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Journalism and Mass Communication', 'JMC');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Kinesiology', 'KINS');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Liberal Studies Elem Education', 'LSEE');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Masters of Business Administration', 'MBA');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Math', 'MATH');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Music', 'MUS');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Native American Studies', 'NAS');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Oceanography', 'OCN');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Philosophy', 'PHIL');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Physical Education', 'PE');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Physics', 'PHYX');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Political Science', 'PSCI');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Psychology', 'PSYC');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Rangeland Resource Science', 'RRS');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Recreation Administration', 'REC');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Religious Studies', 'RS');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Science', 'SCI');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Secondary Education', 'SED');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Social Work', 'SW');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Sociology', 'SOC');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Soils', 'SOIL');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Spanish', 'SPAN');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Special Education', 'SPED');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Statistics', 'STAT');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Theatre Arts', 'TA');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Watershed Management', 'WSHD');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Wildlife', 'WLDF');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Women''s Studies', 'WS');
INSERT INTO studygroups_subject(name, schedule_abbreviation) VALUES('Zoology', 'ZOOL');